 export const countryCodes = [
{ code: "+965", country: "Kuwait", flag: "🇰🇼", iso: "KW", currency: "KWD" },
{ code: "+91", country: "India", flag: "🇮🇳", iso: "IN", currency: "INR" },
{ code: "+93", country: "Afghanistan", flag: "🇦🇫", iso: "AF", currency: "AFN" },
{ code: "+355", country: "Albania", flag: "🇦🇱", iso: "AL", currency: "ALL" },
{ code: "+213", country: "Algeria", flag: "🇩🇿", iso: "DZ", currency: "DZD" },
{ code: "+1-684", country: "American Samoa", flag: "🇦🇸", iso: "AS", currency: "USD" },
{ code: "+376", country: "Andorra", flag: "🇦🇩", iso: "AD", currency: "EUR" },
{ code: "+244", country: "Angola", flag: "🇦🇴", iso: "AO", currency: "AOA" },
{ code: "+1-264", country: "Anguilla", flag: "🇦🇮", iso: "AI", currency: "XCD" },
{ code: "+672", country: "Antarctica", flag: "🇦🇶", iso: "AQ", currency: "NOK" },
{ code: "+1-268", country: "Antigua and Barbuda", flag: "🇦🇬", iso: "AG", currency: "XCD" },
{ code: "+54", country: "Argentina", flag: "🇦🇷", iso: "AR", currency: "ARS" },
{ code: "+374", country: "Armenia", flag: "🇦🇲", iso: "AM", currency: "AMD" },
{ code: "+297", country: "Aruba", flag: "🇦🇼", iso: "AW", currency: "AWG" },
{ code: "+61", country: "Australia", flag: "🇦🇺", iso: "AU", currency: "AUD" },
{ code: "+43", country: "Austria", flag: "🇦🇹", iso: "AT", currency: "EUR" },
{ code: "+994", country: "Azerbaijan", flag: "🇦🇿", iso: "AZ", currency: "AZN" },
{ code: "+1-242", country: "Bahamas", flag: "🇧🇸", iso: "BS", currency: "BSD" },
{ code: "+973", country: "Bahrain", flag: "🇧🇭", iso: "BH", currency: "BHD" },
{ code: "+880", country: "Bangladesh", flag: "🇧🇩", iso: "BD", currency: "BDT" },
{ code: "+1-246", country: "Barbados", flag: "🇧🇧", iso: "BB", currency: "BBD" },
{ code: "+375", country: "Belarus", flag: "🇧🇾", iso: "BY", currency: "BYN" },
{ code: "+32", country: "Belgium", flag: "🇧🇪", iso: "BE", currency: "EUR" },
{ code: "+501", country: "Belize", flag: "🇧🇿", iso: "BZ", currency: "BZD" },
{ code: "+229", country: "Benin", flag: "🇧🇯", iso: "BJ", currency: "XOF" },
{ code: "+1-441", country: "Bermuda", flag: "🇧🇲", iso: "BM", currency: "BMD" },
{ code: "+975", country: "Bhutan", flag: "🇧🇹", iso: "BT", currency: "BTN" },
{ code: "+591", country: "Bolivia", flag: "🇧🇴", iso: "BO", currency: "BOB" },
{ code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦", iso: "BA", currency: "BAM" },
{ code: "+267", country: "Botswana", flag: "🇧🇼", iso: "BW", currency: "BWP" },
{ code: "+55", country: "Brazil", flag: "🇧🇷", iso: "BR", currency: "BRL" },
{ code: "+246", country: "British Indian Ocean Territory", flag: "🇮🇴", iso: "IO", currency: "USD" },
{ code: "+1-284", country: "British Virgin Islands", flag: "🇻🇬", iso: "VG", currency: "USD" },
{ code: "+673", country: "Brunei", flag: "🇧🇳", iso: "BN", currency: "BND" },
{ code: "+359", country: "Bulgaria", flag: "🇧🇬", iso: "BG", currency: "BGN" },
{ code: "+226", country: "Burkina Faso", flag: "🇧🇫", iso: "BF", currency: "XOF" },
{ code: "+257", country: "Burundi", flag: "🇧🇮", iso: "BI", currency: "BIF" },
{ code: "+855", country: "Cambodia", flag: "🇰🇭", iso: "KH", currency: "KHR" },
{ code: "+237", country: "Cameroon", flag: "🇨🇲", iso: "CM", currency: "XAF" },
{ code: "+1", country: "Canada", flag: "🇨🇦", iso: "CA", currency: "CAD" },
{ code: "+238", country: "Cape Verde", flag: "🇨🇻", iso: "CV", currency: "CVE" },
{ code: "+1-345", country: "Cayman Islands", flag: "🇰🇾", iso: "KY", currency: "KYD" },
{ code: "+236", country: "Central African Republic", flag: "🇨🇫", iso: "CF", currency: "XAF" },
{ code: "+235", country: "Chad", flag: "🇹🇩", iso: "TD", currency: "XAF" },
{ code: "+56", country: "Chile", flag: "🇨🇱", iso: "CL", currency: "CLP" },
{ code: "+86", country: "China", flag: "🇨🇳", iso: "CN", currency: "CNY" },
{ code: "+61", country: "Christmas Island", flag: "🇨🇽", iso: "CX", currency: "AUD" },
{ code: "+61", country: "Cocos (Keeling) Islands", flag: "🇨🇨", iso: "CC", currency: "AUD" },
{ code: "+57", country: "Colombia", flag: "🇨🇴", iso: "CO", currency: "COP" },
{ code: "+269", country: "Comoros", flag: "🇰🇲", iso: "KM", currency: "KMF" },
{ code: "+242", country: "Congo (Brazzaville)", flag: "🇨🇬", iso: "CG", currency: "XAF" },
{ code: "+243", country: "Congo (Kinshasa)", flag: "🇨🇩", iso: "CD", currency: "CDF" },
{ code: "+682", country: "Cook Islands", flag: "🇨🇰", iso: "CK", currency: "NZD" },
{ code: "+506", country: "Costa Rica", flag: "🇨🇷", iso: "CR", currency: "CRC" },
{ code: "+225", country: "Côte d'Ivoire", flag: "🇨🇮", iso: "CI", currency: "XOF" },
{ code: "+385", country: "Croatia", flag: "🇭🇷", iso: "HR", currency: "EUR" },
{ code: "+53", country: "Cuba", flag: "🇨🇺", iso: "CU", currency: "CUP" },
{ code: "+599", country: "Curaçao", flag: "🇨🇼", iso: "CW", currency: "ANG" },
{ code: "+357", country: "Cyprus", flag: "🇨🇾", iso: "CY", currency: "EUR" },
{ code: "+420", country: "Czech Republic", flag: "🇨🇿", iso: "CZ", currency: "CZK" },
{ code: "+45", country: "Denmark", flag: "🇩🇰", iso: "DK", currency: "DKK" },
{ code: "+253", country: "Djibouti", flag: "🇩🇯", iso: "DJ", currency: "DJF" },
{ code: "+1-767", country: "Dominica", flag: "🇩🇲", iso: "DM", currency: "XCD" },
{ code: "+1-809", country: "Dominican Republic", flag: "🇩🇴", iso: "DO", currency: "DOP" },
{ code: "+593", country: "Ecuador", flag: "🇪🇨", iso: "EC", currency: "USD" },
{ code: "+20", country: "Egypt", flag: "🇪🇬", iso: "EG", currency: "EGP" },
{ code: "+503", country: "El Salvador", flag: "🇸🇻", iso: "SV", currency: "USD" },
{ code: "+240", country: "Equatorial Guinea", flag: "🇬🇶", iso: "GQ", currency: "XAF" },
{ code: "+291", country: "Eritrea", flag: "🇪🇷", iso: "ER", currency: "ERN" },
{ code: "+372", country: "Estonia", flag: "🇪🇪", iso: "EE", currency: "EUR" },
{ code: "+251", country: "Ethiopia", flag: "🇪🇹", iso: "ET", currency: "ETB" },
{ code: "+500", country: "Falkland Islands (Malvinas)", flag: "🇫🇰", iso: "FK", currency: "FKP" },
{ code: "+298", country: "Faroe Islands", flag: "🇫🇴", iso: "FO", currency: "DKK" },
{ code: "+679", country: "Fiji", flag: "🇫🇯", iso: "FJ", currency: "FJD" },
{ code: "+358", country: "Finland", flag: "🇫🇮", iso: "FI", currency: "EUR" },
{ code: "+33", country: "France", flag: "🇫🇷", iso: "FR", currency: "EUR" },
{ code: "+594", country: "French Guiana", flag: "🇬🇫", iso: "GF", currency: "EUR" },
{ code: "+689", country: "French Polynesia", flag: "🇵🇫", iso: "PF", currency: "XPF" },
{ code: "+262", country: "French Southern Territories", flag: "🇹🇫", iso: "TF", currency: "EUR" },
{ code: "+241", country: "Gabon", flag: "🇬🇦", iso: "GA", currency: "XAF" },
{ code: "+220", country: "Gambia", flag: "🇬🇲", iso: "GM", currency: "GMD" },
{ code: "+995", country: "Georgia", flag: "🇬🇪", iso: "GE", currency: "GEL" },
{ code: "+49", country: "Germany", flag: "🇩🇪", iso: "DE", currency: "EUR" },
{ code: "+233", country: "Ghana", flag: "🇬🇭", iso: "GH", currency: "GHS" },
{ code: "+350", country: "Gibraltar", flag: "🇬🇮", iso: "GI", currency: "GIP" },
{ code: "+30", country: "Greece", flag: "🇬🇷", iso: "GR", currency: "EUR" },
{ code: "+299", country: "Greenland", flag: "🇬🇱", iso: "GL", currency: "DKK" },
{ code: "+1-473", country: "Grenada", flag: "🇬🇩", iso: "GD", currency: "XCD" },
{ code: "+590", country: "Guadeloupe", flag: "🇬🇵", iso: "GP", currency: "EUR" },
{ code: "+1-671", country: "Guam", flag: "🇬🇺", iso: "GU", currency: "USD" },
{ code: "+502", country: "Guatemala", flag: "🇬🇹", iso: "GT", currency: "GTQ" },
{ code: "+44-1481", country: "Guernsey", flag: "🇬🇬", iso: "GG", currency: "GBP" },
{ code: "+224", country: "Guinea", flag: "🇬🇳", iso: "GN", currency: "GNF" },
{ code: "+245", country: "Guinea-Bissau", flag: "🇬🇼", iso: "GW", currency: "XOF" },
{ code: "+592", country: "Guyana", flag: "🇬🇾", iso: "GY", currency: "GYD" },
{ code: "+509", country: "Haiti", flag: "🇭🇹", iso: "HT", currency: "HTG" },
{ code: "+672", country: "Heard Island and McDonald Islands", flag: "🇭🇲", iso: "HM", currency: "AUD" },
{ code: "+39-06", country: "Holy See (Vatican City State)", flag: "🇻🇦", iso: "VA", currency: "EUR" },
{ code: "+504", country: "Honduras", flag: "🇭🇳", iso: "HN", currency: "HNL" },
{ code: "+852", country: "Hong Kong", flag: "🇭🇰", iso: "HK", currency: "HKD" },
{ code: "+36", country: "Hungary", flag: "🇭🇺", iso: "HU", currency: "HUF" },
{ code: "+354", country: "Iceland", flag: "🇮🇸", iso: "IS", currency: "ISK" },
{ code: "+62", country: "Indonesia", flag: "🇮🇩", iso: "ID", currency: "IDR" },
{ code: "+98", country: "Iran", flag: "🇮🇷", iso: "IR", currency: "IRR" },
{ code: "+964", country: "Iraq", flag: "🇮🇶", iso: "IQ", currency: "IQD" },
{ code: "+353", country: "Ireland", flag: "🇮🇪", iso: "IE", currency: "EUR" },
{ code: "+44-1624", country: "Isle of Man", flag: "🇮🇲", iso: "IM", currency: "GBP" },
{ code: "+972", country: "Israel", flag: "🇮🇱", iso: "IL", currency: "ILS" },
{ code: "+39", country: "Italy", flag: "🇮🇹", iso: "IT", currency: "EUR" },
{ code: "+1-876", country: "Jamaica", flag: "🇯🇲", iso: "JM", currency: "JMD" },
{ code: "+81", country: "Japan", flag: "🇯🇵", iso: "JP", currency: "JPY" },
{ code: "+44-1534", country: "Jersey", flag: "🇯🇪", iso: "JE", currency: "GBP" },
{ code: "+962", country: "Jordan", flag: "🇯🇴", iso: "JO", currency: "JOD" },
{ code: "+7", country: "Kazakhstan", flag: "🇰🇿", iso: "KZ", currency: "KZT" },
{ code: "+254", country: "Kenya", flag: "🇰🇪", iso: "KE", currency: "KES" },
{ code: "+686", country: "Kiribati", flag: "🇰🇮", iso: "KI", currency: "AUD" },
{ code: "+996", country: "Kyrgyzstan", flag: "🇰🇬", iso: "KG", currency: "KGS" },
{ code: "+856", country: "Laos", flag: "🇱🇦", iso: "LA", currency: "LAK" },
{ code: "+371", country: "Latvia", flag: "🇱🇻", iso: "LV", currency: "EUR" },
{ code: "+961", country: "Lebanon", flag: "🇱🇧", iso: "LB", currency: "LBP" },
{ code: "+266", country: "Lesotho", flag: "🇱🇸", iso: "LS", currency: "LSL" },
{ code: "+231", country: "Liberia", flag: "🇱🇷", iso: "LR", currency: "LRD" },
{ code: "+218", country: "Libya", flag: "🇱🇾", iso: "LY", currency: "LYD" },
{ code: "+423", country: "Liechtenstein", flag: "🇱🇮", iso: "LI", currency: "CHF" },
{ code: "+370", country: "Lithuania", flag: "🇱🇹", iso: "LT", currency: "EUR" },
{ code: "+352", country: "Luxembourg", flag: "🇱🇺", iso: "LU", currency: "EUR" },
{ code: "+853", country: "Macao", flag: "🇲🇴", iso: "MO", currency: "MOP" },
{ code: "+389", country: "Macedonia (FYROM)", flag: "🇲🇰", iso: "MK", currency: "MKD" },
{ code: "+261", country: "Madagascar", flag: "🇲🇬", iso: "MG", currency: "MGA" },
{ code: "+265", country: "Malawi", flag: "🇲🇼", iso: "MW", currency: "MWK" },
{ code: "+60", country: "Malaysia", flag: "🇲🇾", iso: "MY", currency: "MYR" },
{ code: "+960", country: "Maldives", flag: "🇲🇻", iso: "MV", currency: "MVR" },
{ code: "+223", country: "Mali", flag: "🇲🇱", iso: "ML", currency: "XOF" },
{ code: "+356", country: "Malta", flag: "🇲🇹", iso: "MT", currency: "EUR" },
{ code: "+692", country: "Marshall Islands", flag: "🇲🇭", iso: "MH", currency: "USD" },
{ code: "+596", country: "Martinique", flag: "🇲🇶", iso: "MQ", currency: "EUR" },
{ code: "+222", country: "Mauritania", flag: "🇲🇷", iso: "MR", currency: "MRU" },
{ code: "+230", country: "Mauritius", flag: "🇲🇺", iso: "MU", currency: "MUR" },
{ code: "+262", country: "Mayotte", flag: "🇾🇹", iso: "YT", currency: "EUR" },
{ code: "+52", country: "Mexico", flag: "🇲🇽", iso: "MX", currency: "MXN" },
{ code: "+691", country: "Micronesia", flag: "🇫🇲", iso: "FM", currency: "USD" },
{ code: "+373", country: "Moldova", flag: "🇲🇩", iso: "MD", currency: "MDL" },
{ code: "+377", country: "Monaco", flag: "🇲🇨", iso: "MC", currency: "EUR" },
{ code: "+976", country: "Mongolia", flag: "🇲🇳", iso: "MN", currency: "MNT" },
{ code: "+382", country: "Montenegro", flag: "🇲🇪", iso: "ME", currency: "EUR" },
{ code: "+1-664", country: "Montserrat", flag: "🇲🇸", iso: "MS", currency: "XCD" },
{ code: "+212", country: "Morocco", flag: "🇲🇦", iso: "MA", currency: "MAD" },
{ code: "+258", country: "Mozambique", flag: "🇲🇿", iso: "MZ", currency: "MZN" },
{ code: "+95", country: "Myanmar (Burma)", flag: "🇲🇲", iso: "MM", currency: "MMK" },
{ code: "+264", country: "Namibia", flag: "🇳🇦", iso: "NA", currency: "NAD" },
{ code: "+674", country: "Nauru", flag: "🇳🇷", iso: "NR", currency: "AUD" },
{ code: "+977", country: "Nepal", flag: "🇳🇵", iso: "NP", currency: "NPR" },
{ code: "+31", country: "Netherlands", flag: "🇳🇱", iso: "NL", currency: "EUR" },
{ code: "+687", country: "New Caledonia", flag: "🇳🇨", iso: "NC", currency: "XPF" },
{ code: "+64", country: "New Zealand", flag: "🇳🇿", iso: "NZ", currency: "NZD" },
{ code: "+505", country: "Nicaragua", flag: "🇳🇮", iso: "NI", currency: "NIO" },
{ code: "+227", country: "Niger", flag: "🇳🇪", iso: "NE", currency: "XOF" },
{ code: "+234", country: "Nigeria", flag: "🇳🇬", iso: "NG", currency: "NGN" },
{ code: "+683", country: "Niue", flag: "🇳🇺", iso: "NU", currency: "NZD" },
{ code: "+672", country: "Norfolk Island", flag: "🇳🇫", iso: "NF", currency: "AUD" },
{ code: "+850", country: "North Korea", flag: "🇰🇵", iso: "KP", currency: "KPW" },
{ code: "+47", country: "Norway", flag: "🇳🇴", iso: "NO", currency: "NOK" },
{ code: "+968", country: "Oman", flag: "🇴🇲", iso: "OM", currency: "OMR" },
{ code: "+92", country: "Pakistan", flag: "🇵🇰", iso: "PK", currency: "PKR" },
{ code: "+680", country: "Palau", flag: "🇵🇼", iso: "PW", currency: "USD" },
{ code: "+970", country: "Palestine", flag: "🇵🇸", iso: "PS", currency: "ILS" },
{ code: "+507", country: "Panama", flag: "🇵🇦", iso: "PA", currency: "PAB" },
{ code: "+675", country: "Papua New Guinea", flag: "🇵🇬", iso: "PG", currency: "PGK" },
{ code: "+595", country: "Paraguay", flag: "🇵🇾", iso: "PY", currency: "PYG" },
{ code: "+51", country: "Peru", flag: "🇵🇪", iso: "PE", currency: "PEN" },
{ code: "+63", country: "Philippines", flag: "🇵🇭", iso: "PH", currency: "PHP" },
{ code: "+64", country: "Pitcairn Islands", flag: "🇵🇳", iso: "PN", currency: "NZD" },
{ code: "+48", country: "Poland", flag: "🇵🇱", iso: "PL", currency: "PLN" },
{ code: "+351", country: "Portugal", flag: "🇵🇹", iso: "PT", currency: "EUR" },
{ code: "+1-787", country: "Puerto Rico", flag: "🇵🇷", iso: "PR", currency: "USD" },
{ code: "+974", country: "Qatar", flag: "🇶🇦", iso: "QA", currency: "QAR" },
{ code: "+262", country: "Réunion", flag: "🇷🇪", iso: "RE", currency: "EUR" },
{ code: "+40", country: "Romania", flag: "🇷🇴", iso: "RO", currency: "RON" },
{ code: "+7", country: "Russia", flag: "🇷🇺", iso: "RU", currency: "RUB" },
{ code: "+250", country: "Rwanda", flag: "🇷🇼", iso: "RW", currency: "RWF" },
{ code: "+590", country: "Saint Barthélemy", flag: "🇧🇱", iso: "BL", currency: "EUR" },
{ code: "+290", country: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭", iso: "SH", currency: "SHP" },
{ code: "+1-869", country: "Saint Kitts and Nevis", flag: "🇰🇳", iso: "KN", currency: "XCD" },
{ code: "+1-758", country: "Saint Lucia", flag: "🇱🇨", iso: "LC", currency: "XCD" },
{ code: "+590", country: "Saint Martin (French part)", flag: "🇲🇫", iso: "MF", currency: "EUR" },
{ code: "+508", country: "Saint Pierre and Miquelon", flag: "🇵🇲", iso: "PM", currency: "EUR" },
{ code: "+1-784", country: "Saint Vincent and the Grenadines", flag: "🇻🇨", iso: "VC", currency: "XCD" },
{ code: "+685", country: "Samoa", flag: "🇼🇸", iso: "WS", currency: "WST" },
{ code: "+378", country: "San Marino", flag: "🇸🇲", iso: "SM", currency: "EUR" },
{ code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹", iso: "ST", currency: "STD" },
{ code: "+966", country: "Saudi Arabia", flag: "🇸🇦", iso: "SA", currency: "SAR" },
{ code: "+221", country: "Senegal", flag: "🇸🇳", iso: "SN", currency: "XOF" },
{ code: "+381", country: "Serbia", flag: "🇷🇸", iso: "RS", currency: "RSD" },
{ code: "+248", country: "Seychelles", flag: "🇸🇨", iso: "SC", currency: "SCR" },
{ code: "+232", country: "Sierra Leone", flag: "🇸🇱", iso: "SL", currency: "SLL" },
{ code: "+65", country: "Singapore", flag: "🇸🇬", iso: "SG", currency: "SGD" },
{ code: "+1-721", country: "Sint Maarten (Dutch part)", flag: "🇸🇽", iso: "SX", currency: "ANG" },
{ code: "+421", country: "Slovakia", flag: "🇸🇰", iso: "SK", currency: "EUR" },
{ code: "+386", country: "Slovenia", flag: "🇸🇮", iso: "SI", currency: "EUR" },
{ code: "+677", country: "Solomon Islands", flag: "🇸🇧", iso: "SB", currency: "SBD" },
{ code: "+252", country: "Somalia", flag: "🇸🇴", iso: "SO", currency: "SOS" },
{ code: "+27", country: "South Africa", flag: "🇿🇦", iso: "ZA", currency: "ZAR" },
{ code: "+500", country: "South Georgia and the South Sandwich Islands", flag: "🇬🇸", iso: "GS", currency: "FKP" },
{ code: "+82", country: "South Korea", flag: "🇰🇷", iso: "KR", currency: "KRW" },
{ code: "+211", country: "South Sudan", flag: "🇸🇸", iso: "SS", currency: "SSP" },
{ code: "+34", country: "Spain", flag: "🇪🇸", iso: "ES", currency: "EUR" },
{ code: "+94", country: "Sri Lanka", flag: "🇱🇰", iso: "LK", currency: "LKR" },
{ code: "+249", country: "Sudan", flag: "🇸🇩", iso: "SD", currency: "SDG" },
{ code: "+597", country: "Suriname", flag: "🇸🇷", iso: "SR", currency: "SRD" },
{ code: "+47", country: "Svalbard and Jan Mayen", flag: "🇸🇯", iso: "SJ", currency: "NOK" },
{ code: "+268", country: "Swaziland", flag: "🇸🇿", iso: "SZ", currency: "SZL" },
{ code: "+46", country: "Sweden", flag: "🇸🇪", iso: "SE", currency: "SEK" },
{ code: "+41", country: "Switzerland", flag: "🇨🇭", iso: "CH", currency: "CHF" },
{ code: "+963", country: "Syria", flag: "🇸🇾", iso: "SY", currency: "SYP" },
{ code: "+886", country: "Taiwan", flag: "🇹🇼", iso: "TW", currency: "TWD" },
{ code: "+992", country: "Tajikistan", flag: "🇹🇯", iso: "TJ", currency: "TJS" },
{ code: "+255", country: "Tanzania", flag: "🇹🇿", iso: "TZ", currency: "TZS" },
{ code: "+66", country: "Thailand", flag: "🇹🇭", iso: "TH", currency: "THB" },
{ code: "+670", country: "Timor-Leste", flag: "🇹🇱", iso: "TL", currency: "USD" },
{ code: "+228", country: "Togo", flag: "🇹🇬", iso: "TG", currency: "XOF" },
{ code: "+690", country: "Tokelau", flag: "🇹🇰", iso: "TK", currency: "NZD" },
{ code: "+676", country: "Tonga", flag: "🇹🇴", iso: "TO", currency: "TOP" },
{ code: "+1-868", country: "Trinidad and Tobago", flag: "🇹🇹", iso: "TT", currency: "TTD" },
{ code: "+216", country: "Tunisia", flag: "🇹🇳", iso: "TN", currency: "TND" },
{ code: "+90", country: "Turkey", flag: "🇹🇷", iso: "TR", currency: "TRY" },
{ code: "+993", country: "Turkmenistan", flag: "🇹🇲", iso: "TM", currency: "TMT" },
{ code: "+1-649", country: "Turks and Caicos Islands", flag: "🇹🇨", iso: "TC", currency: "USD" },
{ code: "+688", country: "Tuvalu", flag: "🇹🇻", iso: "TV", currency: "AUD" },
{ code: "+256", country: "Uganda", flag: "🇺🇬", iso: "UG", currency: "UGX" },
{ code: "+380", country: "Ukraine", flag: "🇺🇦", iso: "UA", currency: "UAH" },
{ code: "+971", country: "United Arab Emirates", flag: "🇦🇪", iso: "AE", currency: "AED" },
{ code: "+44", country: "United Kingdom", flag: "🇬🇧", iso: "GB", currency: "GBP" },
{ code: "+1", country: "USA/Canada", flag: "🇺🇸", iso: "US", currency: "USD" },
{ code: "+598", country: "Uruguay", flag: "🇺🇾", iso: "UY", currency: "UYU" },
{ code: "+998", country: "Uzbekistan", flag: "🇺🇿", iso: "UZ", currency: "UZS" },
{ code: "+678", country: "Vanuatu", flag: "🇻🇺", iso: "VU", currency: "VUV" },
{ code: "+58", country: "Venezuela", flag: "🇻🇪", iso: "VE", currency: "VEF" },
{ code: "+84", country: "Vietnam", flag: "🇻🇳", iso: "VN", currency: "VND" },
{ code: "+1-340", country: "Virgin Islands (U.S.)", flag: "🇻🇮", iso: "VI", currency: "USD" },
{ code: "+681", country: "Wallis and Futuna", flag: "🇼🇫", iso: "WF", currency: "XPF" },
{ code: "+212", country: "Western Sahara", flag: "🇪🇭", iso: "EH", currency: "MAD" },
{ code: "+967", country: "Yemen", flag: "🇾🇪", iso: "YE", currency: "YER" },
{ code: "+260", country: "Zambia", flag: "🇿🇲", iso: "ZM", currency: "ZMW" },
{ code: "+263", country: "Zimbabwe", flag: "🇿🇼", iso: "ZW", currency: "ZWL" },
];

